### ISSUE TITLE
Crash with  vanilla tooltip method

### ISSUE THREAD

**Issue by Kuggle01** [skylorbeck/iconicwands#1]
Whenever something calls apon the vanilla tooltip method it crashes the game, like cammie's backpacks for example, which is what was causing the crash for me https://github.com/CammiePone/Cammies-Wearable-Backpacks/blob/1.18-dev/src/main/java/dev/cammiescorner/camsbackpacks/client/screen/BackpackScreen.java#L88

Here is my log after the crash https://paste.ee/p/uw4m1

**Comment by Kuggle01** [comment]
Update: Bundles are also causing the crash

**Comment by skylorbeck** [comment]
Looks like I missed a check to make sure the data for the tooltip is my data. Working on a fix.

**Comment by skylorbeck** [comment]
1.0.3 uploaded, waiting for CurseForge approval. Thank you for the report.

**Comment by skylorbeck** [comment]
Unrelated but ho-ly shit those other mods you have are just throwing errors left and right. Wild.
